### ISSUE TITLE
Circuit is not properly updated when changed by pistons

### ISSUE THREAD

**Issue by bodqhrohro** [minetest-mods/mesecons#502] opened 2020-02-22 19:49 UTC
![mesecons_bug1_comp](https://user-images.githubusercontent.com/2134486/75098264-b52c1880-55bc-11ea-89ec-c4176a828c26.gif)

I see some similar recent issues related to overheat, so maybe it's the cause this time too?

**Comment by DS-Minetest** [comment] 2020-02-22 19:55
I'm able to reproduce.
The pos where the node came from is updated correctly, the destination however isn't.

**Comment by bodqhrohro** [comment] 2020-02-28 00:40
So how to fix it? I tried to replace it with updating both positions:
```
diff --git a/mesecons_mvps/init.lua b/mesecons_mvps/init.lua
index 807692e..dd4e56f 100644
--- a/mesecons_mvps/init.lua
+++ b/mesecons_mvps/init.lua
@@ -239,11 +239,6 @@ function mesecon.mvps_push_or_pull(pos, stackdir, movedir, maximum, all_pull_sti
                minetest.remove_node(n.pos)
        end
 
-       -- update mesecons for removed nodes ( has to be done after all nodes have been removed )
-       for _, n in ipairs(nodes) do
-               mesecon.on_dignode(n.pos, n.node)
-       end
-
        -- add nodes
        for _, n in ipairs(nodes) do
                local np = vector.add(n.pos, movedir)
@@ -267,6 +262,12 @@ function mesecon.mvps_push_or_pull(pos, stackdir, movedir, maximum, all_pull_sti
                moved_nodes[i].node_timer = nodes[i].node_timer
        end
 
+       -- update the moved mesecons
+       for _, n in ipairs(moved_nodes) do
+               mesecon.on_dignode(n.oldpos, n.node)
+               mesecon.on_dignode(n.pos, n.node)
+       end
+
        on_mvps_move(moved_nodes)
 
        return true, nodes, oldstack
```
But it didn't help.

**Comment by numberZero** [comment] 2020-06-26 23:38
Dupe of #406

**Closed by numberZero** 2020-06-26 23:38 UTC
Labels: bug, duplicate
