### ISSUE TITLE
Insulated Mesecon showing up as Unknown Item

### ISSUE THREAD

**Issue by Zippy1** [minetest-mods/mesecons#340] opened 2017-04-16 14:59 UTC
With an insulated mesecon, as soon as you craft it, the item shows up as an unknown item. However: in the inventory the insulated mesecon texture shows up as normal, and you are able to craft things with it, but you are not able to place it.

**Comment by C1ffisme** [comment] 2017-04-16 18:22
> With an insulated mesecon, as soon as you craft it, the item shows up as an unknown item.

Did you actually pull it out of the crafting bench? It's possible that the name for the crafting result was misspelled, and you are actually seeing an unknown item.

**Comment by Zippy1** [comment] 2017-04-17 07:03
Yup, I dragged it into my inventory. It still showed up as an unknown item. (I wouldn't be able to say that people can craft with it otherwise)

**Comment by numberZero** [comment] 2017-04-17 12:51
@Zippy1 make sure you have `mesecons_insulated` enabled.

There seems to be a core bug letting you to use unknown items in craft if the name matches (and to craft them, too). This way, you can e.g. intercraft `mesecons_extrawires:crossover_off`↔`mesecons_insulated:insulated_off`, despite the latter being unknown.

By the way, `mesecons_extrawires` seems to use texture from `mesecons_insulated`, so should depend on it (MT refuses to use a texture from unloaded mod).

**Comment by Wuzzy2** [comment] 2018-01-09 21:08
I can not reproduce this bug as of Mesecons 993fdedd8ccc21610efee00a08e102b38aa34b7e and MT 0.4.16.

**Comment by numberZero** [comment] 2018-01-10 16:46
Fixed by minetest/minetest#6532

**Closed by numberZero** 2018-01-10 16:46 UTC
Labels: bug, core bug
