### ISSUE TITLE
Mesecons don’t handle changing rules well

### ISSUE THREAD

**Issue by numberZero** [minetest-mods/mesecons#372] opened 2017-10-08 16:20 UTC
That includes vertical mesecons, buttons (when they are rotated), etc.
![screenshot_20171008_191338](https://user-images.githubusercontent.com/7352626/31318567-59e70fbc-ac5d-11e7-8954-5a38aa9451df.png)
The buttons have the same `param2`, and wires are in the same places. If I dig and place the wire behind the left button, it connects to the button.

**Comment by DS-Minetest** [comment] 2017-10-08 16:54
The button rotation problem seems only to happen if the wire is already a receiver and should stay a receiver.

**Comment by lolbinarycat** [comment] 2023-12-17 18:08
@Desour what do you mean "stays mounted to the same wall"?

if it is on the wall, it would be connected to the mesecon behind it.

if it is rotated and stays on the wall, it would stay connected, no?

in either case, i have been unable to replicate this bug.  did it get incidentally fixed in a commit somewhere maybe?

**Comment by Desour** [comment] 2023-12-19 18:21
>what do you mean "stays mounted to the same wall"?

IIRC, what I meant was that the big flat side of the button stays at the same side.

>if it is rotated and stays on the wall, it would stay connected, no?

Apparently, it did not.

Will retest later.

**Comment by Desour** [comment] 2023-12-20 13:38
Tested. Issue was fixed by #584.

(I guess my #517 was a duplicate of this issue.)

(To be precise, #584 fixed the rotation case. I wasn't able to reproduce wire connection issues caused by vertical mesecons changing its rules. Everything seems fine.)

**Closed** 2023-12-20 14:12 UTC
Labels: bug
