### ISSUE TITLE
mvps: you can push things out of the edge of the world and pull them back again

### ISSUE THREAD

**Issue by fluxionary** [minetest-mods/mesecons#544] opened 2020-10-10 04:21 UTC
`ignore` nodes seem to be mvps stoppers already, that doesn't help.

**Comment by numberZero** [comment] 2020-10-21 00:42
Explain please, what do you mean by edge of the world?

**Comment by fluxionary** [comment] 2020-10-21 02:33
the areas adjacent to -30912 or 30927 in any dimension (x, y, z)

**Comment by fluxionary** [comment] 2020-10-21 03:11
The very fact that I can push blocks into non-existence and then pull them back again, means that there's something i don't understand about how the minetest engine works. This behaviour doesn't seem to depend on the minetest version, at least for anything vaguely recent (though I haven't tested again since I filed this).

**Comment by numberZero** [comment] 2020-10-21 19:40
The hard limit is [−32768..32767] due to using 16-bit types in many places. The areas you mention are near the map generation limit (which is ±31000) but not the map storage limit. I don’t know whether they contain `ignore` or `air`; the latter would explain the behavior while the former would mean there is indeed a bug. (FYI: `ignore` is in stoppers to prevent damaging actual unloaded areas and not just those off the map)

**Comment by fluxionary** [comment] 2020-10-21 21:28
I'll try to explain this again. I assumed the mapblocks outside [-30912,30927] were forced to be unloaded; this doesn't seem to be exactly the case though. Usually, if I do a `minetest.get_node` on an area outside those bounds, it comes back as "ignore". If I try to pull nodes out of the void, i get nothing. However, I can still somehow push things into it; then, If I do a `get_node`, it gives me the name of the block (which I can't see). I can also pull it back, and when I do, that node outside the map now contains `air`. 

Here's some pictures:

A regular node outside the map is `ignore`:
![screenshot_20201021_140440](https://user-images.githubusercontent.com/25628292/96788248-0983d400-13a8-11eb-842c-16698a8ef5b3.png)

A snowblock has been pushed outside the map:
![screenshot_20201021_140530](https://user-images.githubusercontent.com/25628292/96788356-3c2dcc80-13a8-11eb-95a2-92ca9080bfce.png)

The head of an activated piston is outside the map:
![screenshot_20201021_140552](https://user-images.githubusercontent.com/25628292/96788387-49e35200-13a8-11eb-8948-96986c751af4.png)

After pushing a sequence of 16 snowblocks outside the map:
![screenshot_20201021_141126](https://user-images.githubusercontent.com/25628292/96788423-55367d80-13a8-11eb-9e10-d8033f33b359.png)

Fortunately piston push limits are capped at 15 and movestones at 50; I feel like pushing things beyond the 16 bit limit would cause more serious problems. 

And for the record, I absolutely consider being able to "hide" things outside the map to be a bug.

**Comment by Desour** [comment] 2020-10-22 20:47
I tried to reproduce (with success) and debugged with print statements.
The problem is that `node_replaceable` returns `true` for `"ignore"` because it seems to be `buildable_to`:
https://github.com/minetest-mods/mesecons/blob/d356f901a3c26f2cce28ce0be64d26fff996e110/mesecons_mvps/init.lua#L56-L63

**Comment by Desour** [comment] 2020-10-22 20:58
PR: #545

**Comment by numberZero** [comment] 2020-10-23 17:17
So,

> there is indeed a bug

I thought it was fixed already, it had been causing havoc since ever.

**Comment by numberZero** [comment] 2020-10-23 17:38
Dupe of #433

**Closed by numberZero** 2020-10-23 17:38 UTC
Labels: bug, duplicate
