### ISSUE TITLE
Regression caused by b46c589

### ISSUE THREAD

**Issue by appgurueu** [minetest-mods/mesecons#684] opened 2024-10-16 22:08 UTC
See https://forum.minetest.net/viewtopic.php?p=439964#p439964:

> After downloading the latest update to this mod on 10/16/24, the mod is crashing the game with the following error:
> 
> ```
> ModError: Runtime error from mod 'mesecons_doors' in callback on_mods_loaded(): ...64\minetest\bin\..\mods\mesecons\mesecons_doors\init.lua:135: bad argument #1 to 'pairs' (table expected, got nil)
> stack traceback:
> [C]: in function 'pairs'
> ...64\minetest\bin\..\mods\mesecons\mesecons_doors\init.lua:135: in function <...64\minetest\bin\..\mods\mesecons\mesecons_doors\init.lua:134>
> ...t 5.4.1 -win64\minetest\bin\..\builtin\game\register.lua:431: in function <...t 5.4.1 -win64\minetest\bin\..\builtin\game\register.lua:417>
> ```

The line in question: https://github.com/minetest-mods/mesecons/blob/b46c589a38c98b4fe84716922dbabb21841bca67/mesecons_doors/init.lua#L135

Just a simple `or {}` should fix it. Same should be done right below. Though I do wonder what would cause `doors.registered_doors` to be `nil` despite `mesecons_doors` depending on `doors`. Maybe there is an API-incompatible mod called `doors` out there?

**Comment by Niklp09** [comment] 2024-10-17 09:00
https://content.minetest.net/modnames/doors/
Tested TenPlus1's doors_redo. Their mod works fine and provides the required table.

**Comment by sfan5** [comment] 2024-10-17 13:26
Before simply adding a nil check we should find out the cause.

**Comment by Niklp09** [comment] 2024-10-17 13:57
>Before simply adding a nil check we should find out the cause.

That's why [I asked](https://forum.minetest.net/viewtopic.php?p=439974&sid=3d584fc6aa3f538abed6bbe5c7488d60#p439974) the initial reporter in the forums for more information.

**Comment by sfan5** [comment] 2024-12-07 14:54
Closing as invalid.

**Closed by sfan5** 2024-12-07 14:54 UTC
Labels: bug
